joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: hokuyo_joint
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: back_bkz
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: back_bky
  pid: {p: 10.0, i: 0.1, d: 30.0}

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: back_bkx
  pid: {p: 10.0, i: 0.1, d: 30.0}  
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_arm_elx
  pid: {p: 0.1, i: 0.01, d: 30.0}

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_arm_ely
  pid: {p: 0.1, i: 0.01, d: 30.0}

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_arm_wrx
  pid: {p: 10.0, i: 0.01, d: 10.0}

joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_arm_shx
  pid: {p: 5000.0, i: 0.01, d: 10.0}

joint9_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_arm_wry
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint10_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_kny
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint11_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_akx
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint12_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_hpy
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint13_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_hpx
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint14_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_aky
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint15_position_controller:
  type: effort_controllers/JointPositionController
  joint: l_leg_hpz
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint16_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_ry
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint17_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_arm_elx
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint18_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_arm_ely
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint19_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_arm_wrx
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint20_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_hpz
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint21_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_arm_shx
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint22_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_arm_wry
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint23_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_kny
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint24_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_akx
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint25_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_hpy
  pid: {p: 0.1, i: 0.01, d: 10.0}
joint26_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_hpx
  pid: {p: 0.1, i: 0.01, d: 10.0}

joint27_position_controller:
  type: effort_controllers/JointPositionController
  joint: r_leg_aky
  pid: {p: 0.1, i: 0.01, d: 10.0}

