atlas:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250 
    
  vel_based_pos_traj_controller:
      type: velocity_controllers/JointTrajectoryController
      joints: 
        - hokuyo_joint 
        - back_bkz
        - back_bky
        - back_bkx
        - l_arm_elx
        - l_arm_ely
        - l_arm_wrx
        - l_arm_shx
        - l_arm_wry
        - l_leg_kny
        - l_leg_akx
        - l_leg_hpy
        - l_leg_hpx
        - l_leg_aky
        - l_leg_hpz
        - neck_ry
        - r_arm_elx
        - r_arm_ely
        - r_arm_wrx
        - r_leg_hpz
        - r_arm_shx
        - r_arm_wry
        - r_leg_kny
        - r_leg_akx
        - r_leg_hpy
        - r_leg_hpx
        - r_leg_aky


      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        hokuyo_joint: {trajectory: 0.1, goal: 0.1}
        back_bkz: {trajectory: 0.1, goal: 0.1}
        back_bky: {trajectory: 0.1, goal: 0.1}
        back_bkx: {trajectory: 0.1, goal: 0.1}
        l_arm_elx: {trajectory: 0.1, goal: 0.1}
        l_arm_ely: {trajectory: 0.1, goal: 0.1}
        l_arm_wrx: {trajectory: 0.1, goal: 0.1}
        l_arm_shx: {trajectory: 0.1, goal: 0.1}
        l_arm_wry: {trajectory: 0.1, goal: 0.1}
        l_leg_kny: {trajectory: 0.1, goal: 0.1}
        l_leg_akx: {trajectory: 0.1, goal: 0.1}
        l_leg_hpy: {trajectory: 0.1, goal: 0.1}
        l_leg_hpx: {trajectory: 0.1, goal: 0.1}
        l_leg_aky: {trajectory: 0.1, goal: 0.1}
        l_leg_hpz: {trajectory: 0.1, goal: 0.1}
        neck_ry: {trajectory: 0.1, goal: 0.1}
        r_arm_elx: {trajectory: 0.1, goal: 0.1}
        r_arm_ely: {trajectory: 0.1, goal: 0.1}
        r_arm_wrx: {trajectory: 0.1, goal: 0.1}
        r_leg_hpz: {trajectory: 0.1, goal: 0.1}
        r_arm_shx: {trajectory: 0.1, goal: 0.1}
        r_arm_wry: {trajectory: 0.1, goal: 0.1}
        r_leg_kny: {trajectory: 0.1, goal: 0.1}
        r_leg_akx: {trajectory: 0.1, goal: 0.1}
        r_leg_hpy: {trajectory: 0.1, goal: 0.1}
        r_leg_hpx: {trajectory: 0.1, goal: 0.1}
        r_leg_aky: {trajectory: 0.1, goal: 0.1}


      stop_trajectory_duration: 0.5
      state_publish_rate:  125
      action_monitor_rate: 10
      gains:
        #!!These values are useable, but maybe not optimal
        hokuyo_joint: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        back_bkz: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        back_bky: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        back_bkx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_arm_elx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_arm_ely: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_arm_wrx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_arm_shx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_arm_wry: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_kny: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_akx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_hpy: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_hpx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_aky: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        l_leg_hpz: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        neck_ry: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_arm_elx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_arm_ely: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_arm_wrx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_hpz: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_arm_shx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_arm_wry: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_kny: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_akx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_hpy: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_hpx: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}
        r_leg_aky: {p: 20.0,  i: 0.0, d: 0.1, i_clamp: 1}

